#!/bin/bash

# Released under the terms of GPLv3 or at your option any later version.
# No warranties.
# Copyright 2009 Enrico Tassi <gares@fettunta.org>

set -e

# The config file name
CONFFILE=~/.smd/loop

# The length of a minute, decrease to debug
MINUTE=60

# The clock, incremented every $MINUTE
TIME=1

# Verbose
VERBOSE=0

if [ "$1" = "-v" ]; then
	VERBOSE=1
fi

perform() {
	local cmd=$1
	local endpoint=$2

	local cmd_line="$cmd -v $endpoint"
	if [ "$VERBOSE" = 1 ]; then
		echo smd-loop: $cmd_line
	fi
	$cmd_line
}

if [ ! -f $CONFFILE ]; then
	cat > $CONFFILE <<-EOT
	# smd-loop configuration file
	#
	# Line starting with '#' are comments.
	# Frequences are in minutes.
	#
	# pull-frequency push-frequency endpoint-name
	  3              10             default
	EOT

	echo No config file found: created a default one
	echo Please edit it: $CONFFILE
	exit 1
fi

while true; do
	while read pull push endpoint; do
		do_pull=1
		do_push=1
		if [ $pull -gt 0 ]; then do_pull=$((TIME % pull)); fi
		if [ $push -gt 0 ]; then do_push=$((TIME % push)); fi
	
		if [ $do_pull -eq 0 ]; then perform smd-pull $endpoint; fi
		if [ $do_push -eq 0 ]; then perform smd-push $endpoint; fi
	done < <(grep -v '^#' $CONFFILE)
	TIME=$((TIME+1))
	sleep $MINUTE 
done
