#!/bin/sh
#
# Released under the terms of GPLv3 or at your option any later version.
# No warranties.
# Copyright 2011 Enrico Tassi <gares@fettunta.org>

#set -x

SSH="@SSH@"
if [ `echo "$SSH" | cut -c -1` = "@" ]; then
	SSH=ssh
	echo "`basename $0` not installed, assuming secure shell client is $SSH"
fi

PREFIX="@PREFIX@"
MDDIFF=$PREFIX/bin/mddiff
if [ `echo "$PREFIX" | cut -c -1` = "@" ]; then
	MDDIFF=./mddiff
	echo "`basename $0` not installed, assuming mddiff is $MDDIFF"
fi

REPNAME=default

if [ ! -z "$1" ]; then
	REPNAME="$1"
fi

. ~/.smd/config.$REPNAME

if [ -z "$MAILBOX_LOCAL" ]; then
	MAILBOX_LOCAL="$MAILBOX"
fi
if [ -z "$MAILBOX_REMOTE" ]; then
	MAILBOX_REMOTE="$MAILBOX"
fi
if [ -z "$TRANSLATOR_LR" -o -z "$TRANSLATOR_RL" ]; then
	echo Endpoint $REPNAME is not configured to use translators	
	exit 1
fi

cd

TL=`mktemp`
TR=`mktemp`

echo Local mailboxes translated to remote and back:
$MDDIFF -l $MAILBOX_LOCAL > $TL
if [ ! $? -eq 0 ]; then
	echo Error while listing the content of $MAILBOX_LOCAL, skipping
else
	while read M; do
		MM="`$TRANSLATOR_LR "$M" | head -n 1`"
		MMM="`$TRANSLATOR_RL "$MM" | head -n 1`"
		echo "  " $M "->" $MM "->" $MMM
		if [ "$M" != "$MMM" ]; then
			echo Failed round trip check: $M "->" $MMM
			echo "  " $TRANSLATOR_LR "$M" "->" $MM
			echo "  " $TRANSLATOR_RL "$MM" "->" $MMM
			exit 1
		fi
	done < $TL
fi
echo
echo Remote mailboxes translated to local and back:
$SSH $SERVERNAME $MDDIFF -l $MAILBOX_REMOTE > $TR
if [ ! $? -eq 0 ]; then
	echo Error while listing the content of $MAILBOX_REMOTE, skipping
else
	while read M; do
		MM="`$TRANSLATOR_RL "$M" | head -n 1`"
		MMM="`$TRANSLATOR_LR "$MM" | head -n 1`"
		echo "  " $M "->" $MM "->" $MMM
		if [ "$M" != "$MMM" ]; then
			echo Failed round trip check: $M "->" $MMM
			echo "  " $TRANSLATOR_RL "$M" "->" $MM
			echo "  " $TRANSLATOR_LR "$MM" "->" $MMM
			exit 1
		fi
	done < $TR
fi

rm $TL $TR

exit 0

# vim:ts=4:
