#!/bin/sh
#
# Released under the terms of GPLv3 or at your option any later version.
# No warranties.
# Copyright Enrico Tassi <gares@fettunta.org>

# the idea is (where == is a bi-directional pipe) :
#
#   ssh foo smd-client == tee log == smd-server
#

set -e
#set -x

PREFIX="@PREFIX@"
if [ `echo "$PREFIX" | cut -c -1` = "@" ]; then
	SMDROOT=.
	echo "smd-pull not installed, assuming smd-common is ./smd-common"
else
	SMDROOT=$PREFIX/share/syncmaildir
fi

. $SMDROOT/smd-common

init
parse_args "$@"
read_conffile
# this could be a system wide pre-hook
check_lockfile
setup_plumbing
setup_logging
setup_mailboxnames

# we move to the home, since Mail paths are relative
# to the home
cd

# reset log file before caclling hooks
> $CL

run_hooks $CONFDIR pre push 0

($MITM $CtS > $LtS) < $CtL &
LOGGER1=$!
atexit_kill $LOGGER1

($MITM $StC > $LtC) < $StL &
LOGGER2=$!
atexit_kill $LOGGER2

($PROGRESS_REPORTER $SL) < $PRp &
REPORTER=$!
atexit_kill $REPORTER

setup_workarea

(cd $WORKAREA; $SMDSERVER $CHILDSARGS $CLIENTNAME $MAILBOX_REMOTE < $LtC 2>> $CL) > $CtL &
CLIENT=$!
atexit_kill $CLIENT

EXITCODE=0
($SSH $SERVERNAME $REMOTESMDCLIENT $CHILDSARGS $CLIENTNAME $MAILBOX_REMOTE < $LtS 2> $PRp) > $StL || EXITCODE=1

wait $CLIENT || EXITCODE=1 

run_hooks $CONFDIR post push $EXITCODE

report $EXITCODE $SHOWTAGS smd-push smd-pull smd-server smd-client

exit $EXITCODE
