#!/bin/bash

# the idea is (where == is a bi-directional pipe) :
#
#   ssh foo smd-client == tee log == smd-server
#

set -e
#set -x
cd

PREFIX="@PREFIX@"
if [ `echo $PREFIX | cut -c -1` = "@" ]; then
	SMDROOT=~/Projects/syncmaildir
	echo "smd-push not installed, assuming smd-common is in $SMDROOT"
else
	SMDROOT=$PREFIX/share/syncmaildir
fi

. $SMDROOT/smd-common

($MITM $CtS > $LtS) < $CtL &
LOGGER1=$!

($MITM $StC > $LtC) < $StL &
LOGGER2=$!

($SMDSERVER $VERBOSE $CLIENTNAME $MAILBOX < $LtC 2> $CL) > $CtL &
CLIENT=$!

($SSH $SERVERNAME $SMDCLIENT $VERBOSE $CLIENTNAME $MAILBOX < $LtS 2> $SL) > $StL &
SERVER=$!

EXITCODE=0
wait $SERVER || EXITCODE=1
wait $CLIENT || EXITCODE=1 

if [ $EXITCODE = 1 ]; then
	grep ^ERROR $CL \
		| sed 's/^/smd-server: /'
	grep ^ERROR $SL \
		| sed 's/^/smd-client: /'
	grep ^ssh: $SL \
		| sed 's/^/smd-client: ERROR: /'
fi
if [ $SHOWTAGS = 1 ]; then
	grep ^TAGS $CL \
		| sed "s/^/$REPNAME: smd-server@localhost: /" \
		| sed "s/@@INVERSECOMMAND@@/smd-pull/" \
		| sed "s/@@ENDPOINT@@/$REPNAME/"
	grep ^TAGS $SL \
		| sed "s/^/$REPNAME: smd-client@$SERVERNAME: /" \
		| sed "s/@@INVERSECOMMAND@@/smd-pull/" \
		| sed "s/@@ENDPOINT@@/$REPNAME/"
	if [ `grep ^TAGS $SL|wc -l` = 0 ] && \
	   [ `grep ^TAGS $CL|wc -l` = 0 ]; then
		# it may be that ssh failed to resolve the hostname
		# so we generate a fake tag for it
		echo "$REPNAME: smd-client@$SERVERNAME: TAGS: error::context(ssh) probable-cause(network) human-intervention(avoidable) suggested-actions(retry)"
	fi

fi

exit $EXITCODE
