#!/bin/bash

cd $ROOT/test.$N

msync 1

mv Mail/cur/`ls Mail/cur/ | head -n 1` Mail/cur/moved_here

msync 2

test_eq Mail target/Mail 

X=`grep '^DELETE ' log.s2c | wc -l`
assert $X 1 "missing DELETE in s2c"

X=`grep '^COPY ' log.s2c | wc -l`
assert $X 1 "missing COPY in s2c"

X=`grep '^COMMIT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"
