#!/bin/sh

cd $ROOT/test.$N

msync 1

sed -i 's/^Subject:.*$/Subject: PIPPO/' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i 's/^Subject:.*$/Subject: PLUTO/' target/Mail/cur/`ls Mail/cur/ | head -n 1`
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 

X=`grep '^REPLACEHEADER ' log.s2c | wc -l`
assert $X 1 "missing REPLACEHEADER in s2c"

X=`grep '^GETHEADER ' log.c2s | wc -l`
assert $X 0 "GETHEADER present in c2s, should not"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing ABORT in c2s"

