#!/bin/sh

cd $ROOT/test.$N

msync 1

sed -i 's/^Subject:.*$/Subject: PIPPO/' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i 's/^Subject:.*$/Subject: PLUTO/' target/Mail/cur/`ls Mail/cur/ | head -n 1`
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 

