#!/bin/bash

cd $ROOT/test.$N

msync 1

cp Mail/cur/`ls Mail/cur/ | tail -n 1` target/Mail/cur/copied_here
cp Mail/cur/`ls Mail/cur/ | head -n 1` Mail/cur/copied_here
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 
X=`grep '^COPY ' log.s2c | wc -l`
assert $X 1 "missing COPY in s2c"

X=`grep '^GET ' log.c2s | wc -l`
assert $X 0 "GET in c2s, should not"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing ABORT in c2s"
