#!/bin/bash

cd $ROOT/test.$N

msync 1

rm Mail/cur/`ls Mail/cur/ | head -n 1`
rm target/Mail/cur/`ls target/Mail/cur/ | head -n 1`

msync 2

test_eq Mail target/Mail 
X=`grep '^DELETE ' log.s2c | wc -l`
if [ $X = 1 ]; then
	echo -n '.'
else
	echo 'ERROR: no COPY/DELETE'
	exit 1
fi
