#!/bin/bash

cd $ROOT/test.$N

msync 1

echo -en 'Subject: aa\n\nBody\n' >  Mail/cur/new_mail
echo -en 'Subject: bb\n\nBody\n' >  target/Mail/cur/new_mail
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 

X=`grep '^ADD ' log.s2c | wc -l`
assert $X 1 "missing ADD in s2c"

X=`grep '^GET ' log.c2s | wc -l`
assert $X 0 "GET in c2s, should not"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing ABORT in c2s"
