#!/bin/bash

cd $ROOT/test.$N

msync 1

sed -i 's/^Subject.*$/Subject: foo/' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i '$ a foo' Mail/cur/`ls Mail/cur/ | head -n 1`

msync 2

test_eq Mail target/Mail 

X=`grep '^REPLACE ' log.s2c | wc -l`
assert $X 1 "missing REPLACE in s2c"

X=`grep '^ADD ' log.s2c | wc -l`
assert $X 0 "REPLACE+ADD in s2c"

X=`grep '^GETHEADER ' log.c2s | wc -l`
assert $X 0 "GETHEADEr in c2s, should not"

X=`grep '^GET ' log.c2s | wc -l`
assert $X 1 "no GET in c2s"

X=`grep '^COMMIT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"
