#!/bin/bash

cd $ROOT/test.$N

msync 1


sed -i 's/^Subject.*$/Subject: foo/' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i '$ a foo' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i 's/^Subject.*$/Subject: bar/' target/Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i '$ a bar' target/Mail/cur/`ls Mail/cur/ | head -n 1`
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 

X=`grep '^REPLACE ' log.s2c | wc -l`
assert $X 1 "missing REPLACE in s2c"

X=`grep '^GET ' log.c2s | wc -l`
assert $X 0 "GET in c2s"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing ABORT in c2s"
