#!/bin/bash
#
# BASE: where you can run make/make install
# TESTSUITE: client-server, pull-push

#set -x
VALGRIND="valgrind --log-file=log.valgrind --leak-check=no --error-exitcode=1 --"

ROOT=$BASE/tests.d/run/$TESTSUITE/

TOKILL=""

if [ ! -z "$VALGRIND" ]; then
	if which valgrind >/dev/null 2>&1; then
	       :
      	else
		echo 'VALGRIND set but not installed. Disabling it'
		VALGRIND=
	fi
fi

out(){
	(
	for P in $TOKILL; do
		kill $P
	done
	) 2>/dev/null
}

trap out EXIT

test_eq(){
	if diff -ruN $1 $2 >/dev/null; then
		echo -n .
	else
		echo ERROR: diff
		exit 1
	fi
}

run_server(){
	HOME=$ROOT/$TESTSUITE/$N/ \
	PATH=$ROOT/$TESTSUITE/$N/bin:$PATH \
	LUA_INIT="package.path='$ROOT/$TESTSUITE/$N/share/lua/5.1/?.lua;'" \
		smd-server -v test Mail < c2s 2> log.server.$1 \
		| tee log.s2c > s2c &
	RC=$!
	TOKILL="$TOKILL $RC"
}

run_client(){
	cd target 
	HOME=$ROOT/$TESTSUITE/$N/target \
	PATH=$ROOT/$TESTSUITE/$N/bin:$PATH \
	LUA_INIT="package.path='$ROOT/$TESTSUITE/$N/share/lua/5.1/?.lua;'" \
		smd-client -v test Mail < ../s2c 2> ../log.client.$1 \
		| tee ../log.c2s > ../c2s &
	RC=$!
	TOKILL="$TOKILL $RC"
	cd ..
}

msync(){
	run_server $N
	local SERVER=$RC
	run_client $N
	local CLIENT=$RC
	
	wait $SERVER
	wait $CLIENT
}

mpull(){
	LUA_INIT="package.path='$ROOT/$TESTSUITE/$N/share/lua/5.1/?.lua;'" \
	HOME=$ROOT/$TESTSUITE/$N/target \
	HOMES=$ROOT/$TESTSUITE/$N/ \
		$ROOT/$TESTSUITE/$N/bin/smd-pull $@ > log.pull 2>&1
}

mdiff(){
	LUA_INIT="package.path='$ROOT/$TESTSUITE/$N/share/lua/5.1/?.lua;'" \
	HOME=$ROOT/$TESTSUITE/$N/ \
		$VALGRIND $ROOT/$TESTSUITE/$N/bin/mddiff $@ > log.mddiff 2>&1
}

assert(){
	if [ "$1" = "$2" ]; then
		echo -n '.'
	else
		echo 'ERROR: ' $3
		exit 1
	fi
}

prepare(){
	local N=$1

	cd $BASE
	rm -rf $ROOT/$TESTSUITE/$N
	mkdir -p $ROOT/$TESTSUITE/$N/target
	make --quiet
	make --quiet install-bin \
		SSH=$ROOT/$TESTSUITE/$N/bin/fakessh \
		PREFIX=$ROOT/$TESTSUITE/$N

	cat > $ROOT/$TESTSUITE/$N/bin/fakessh <<-EOT
	#!/bin/sh
	shift
	cd \$HOMES
	HOME=\$HOMES \$@
	EOT
	chmod a+x $ROOT/$TESTSUITE/$N/bin/fakessh
	
	cd $ROOT/$TESTSUITE/$N
	tar -xzf $BASE/misc/Mail.testcase.tgz
	mkfifo s2c
	mkfifo c2s
}

run_test() {
	local T="$1"
	echo -n "running $TESTSUITE/`basename $T`: "
	local N=`echo $T | sed 's/^[^0-9]*\([0-9][0-9]*\).*$/\1/'`
	prepare $N
	cd $ROOT/$TESTSUITE/$N
	. $T
	echo OK
}

run_tests() {
	local testfile="$1"
	if [ ! -z "$testfile" ]; then
		if [ -f $testfile ] && 
		   (echo $testfile | grep $TESTSUITE > /dev/null); then
			run_test $testfile
		fi
	else
		for T in $BASE/tests.d/$TESTSUITE/[0-9]*; do
			run_test $T
		done
	fi
}
