#!/bin/sh


msync 1

sed -i 's/^Subject:.*$/Subject: PIPPO/' Mail/cur/`ls Mail/cur/ | head -n 1`

msync 2

test_eq Mail target/Mail 

X=`grep '^REPLACEHEADER ' log.s2c | wc -l`
assert $X 1 "missing REPLACEHEADER in s2c"

X=`grep '^GETHEADER ' log.c2s | wc -l`
assert $X 1 "missing GETHEADER in c2s"

X=`grep '^COMMIT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"

