#!/bin/bash


msync 1

rm Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i 's/Subject/Subbbbbbject/' target/Mail/cur/`ls target/Mail/cur/ | head -n 1`
cp -r target/Mail target/Mail.old

msync 2

test_eq target/Mail.old target/Mail 

X=`grep '^DELETE ' log.s2c | wc -l`
assert $X 1 "missing DELETE in s2c"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing ABORT in c2s"

