#!/bin/bash


msync 1

echo -en 'Subject: foo\n\nBODY\n' > Mail/cur/new_mail
cp -r target/Mail/ target/Mail.old
chmod a-w target/Mail/cur

msync 2

chmod u+w target/Mail/cur

test_eq target/Mail.old target/Mail 

X=`grep '^ADD ' log.s2c | wc -l`
assert $X 1 "missing ADD in s2c"

X=`grep '^ABORT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"

