#!/bin/bash


msync 1

sed -i 's/^Subject.*$/Subject: foo/' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i '$ a foo' Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i 's/^Subject.*$/Subject: foo/' target/Mail/cur/`ls Mail/cur/ | head -n 1`
sed -i '$ a foo' target/Mail/cur/`ls Mail/cur/ | head -n 1`

msync 2

test_eq Mail target/Mail 

X=`grep '^REPLACE ' log.s2c | wc -l`
assert $X 1 "missing REPLACE in s2c"

X=`grep '^GET ' log.c2s | wc -l`
assert $X 0 "GET in c2s"

X=`grep '^COMMIT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"
