#!/bin/bash


msync 1

test_eq Mail target/Mail 

mkdir -p "Mail/very bad/cur"
mkdir "Mail/very bad/new"
mkdir "Mail/very bad/tmp"
cp Mail/cur/`basename $(ls Mail/cur|head -1)` 'Mail/very bad/cur/foo %'
mv Mail/cur/`basename $(ls Mail/cur|head -1)` 'Mail/cur/foo %'

msync 2

test_eq Mail target/Mail

