#!/bin/bash


msync 1

M=Mail/cur/`ls Mail/cur/ | head -n 1`

mv $M Mail/cur/copied_here
cp target/$M target/Mail/cur/copied_here
sed -i 's/a/z/' target/$M

msync 2

X=`grep '^MOVE ' log.s2c | wc -l`
assert $X 1 "missing MOVE in s2c"

X=`grep '^COMMIT$' log.c2s | wc -l`
assert $X 1 "missing COMMIT in c2s"
