#!/bin/bash

run_server(){
	HOME=$HOMES smd-server -v test Mail < c2s 2> log.server.$1 | tee log.s2c > s2c &
	SERVER=$!
	TOKILL="$TOKILL $SERVER"
}

run_client(){
	cd target 
	HOME=$HOMEC smd-client -v test Mail < ../s2c 2> ../log.client.$1 | tee ../log.c2s > ../c2s &
	CLIENT=$!
	TOKILL="$TOKILL $CLIENT"
	cd ..
}

wait_server(){
	wait $SERVER 
}

wait_client(){
	wait $CLIENT
}

msync(){
	run_server $N
	run_client $N
	
	wait_server
	wait_client
}

assert(){
	if [ "$1" = "$2" ]; then
		echo -n '.'
	else
		echo 'ERROR: ' $3
		exit 1
	fi
}
