#!/bin/sh

mpull -t
assert $? 0 "failed mpull -t"
echo DEBUG=true >> target/.smd/config.default

mpull
assert $? 0 "failed mpull"

muniform -v
assert $? 1 "muniform does not fail even if already sync"

