#!/bin/sh

mpull -t
assert $? 0 "failed mpull -t"
echo DEBUG=true >> target/.smd/config.default

mpull 
assert $? 0 "failed mpull"
cp -r target/Mail target/Mail.backup
sed -i 's/^Subject:.*$/Subject: PIPPO/' Mail/cur/`ls Mail/cur/ | head -n 1`

mpull --dry-run
assert $? 0 "failed mpull --dry-run"
test_eq target/Mail.backup target/Mail

