#!/bin/sh

mpull -t 
cat > target/.smd/hooks/post-pull.d/01-test <<EOT
echo \$@ 1>&2
EOT
chmod a+x target/.smd/hooks/post-pull.d/01-test
mpull 
grep 'post pull default 0' target/.smd/log/client.default.log > /dev/null
assert $? 0 "hook output not redirected to log file"

