#!/bin/sh

mv Mail target/

mpush -t
assert $? 0 "failed mpush -t"

mpush -v
assert $? 0 "failed mpush -v"
test_eq Mail target/Mail 
W=`grep '^Phase.[0-9]:' log.push | wc -l`
assert $W 4 "bad log, not 4 Phases"

mpush -s
assert $? 0 "failed mpush -v"
test_eq Mail target/Mail 
W=`grep '^Phase.[0-9]:' log.push | wc -l`
assert $W 0 "bad log, not 0 Phases"
