#!/bin/sh

mpull -t
assert $? 0 "failed mpull -t"
echo DEBUG=true >> target/.smd/config.default
echo SERVERNAME=localhost >> target/.smd/config.default
echo SMDCLIENTOPTS=-l >> target/.smd/config.default
echo MAILBOX= >> target/.smd/config.default
echo MAILBOX_LOCAL=MailBK >> target/.smd/config.default
echo MAILBOX_REMOTE=Mail >> target/.smd/config.default
echo "TRANSLATOR_RL=\"smd-translate -m move -d RL default\"" >> target/.smd/config.default
echo "TRANSLATOR_LR=\"smd-translate -m move -d LR default\"" >> target/.smd/config.default

mv Mail target/

mcheck

mpull
assert $? 0 "failed mpull"
test_eq target/Mail target/MailBK 

mpull
assert $? 0 "failed 2nd mpull"
test_eq target/Mail target/MailBK

mpush
assert $? 0 "failed mpush"
test_eq target/Mail target/MailBK
