#!/bin/sh

mpull -t
assert $? 0 "failed mpull -t"
echo DEBUG=true >> target/.smd/config.default

mpull
assert $? 0 "failed mpull"
test_eq Mail target/Mail 

cp -r target/Mail target/Mail.bak
rm Mail/cur/`ls Mail/cur|head -n1`
mpull -n
assert $? 0 "failed mpull after deletion"
test_eq target/Mail target/Mail.bak 
mpull -n
assert $? 0 "failed mpull after deletion"
test_eq target/Mail target/Mail.bak 

