#!/bin/sh

mpull -t
assert $? 0 "failed mpull -t"
echo DEBUG=true >> target/.smd/config.default

mkdir 'Mail/foo & bar'
mv Mail/cur 'Mail/foo & bar/'

mpull
assert $? 0 "failed mpull"
test_eq Mail target/Mail 
